### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by licengkuri** [platomav/BIOSUtilities#1]
tested for new generation not work .am tested with extracted dell vostro 5459 not working.please update .thanks for all

**Comment by platomav** [comment]
Dell has way too many types/generations of "HDR" structures. This script, HDR Module Extractor, works on modern icon-less executables. That Vostro system is not modern enough. Use PhoenixTool or the -writehdrfile etc parameters instead.

**Comment by licengkuri** [comment]
Thanks master
