### ISSUE TITLE
Alienware_ x15_ X17 cannot use Dell_ PFS_ Extract extract.

### ISSUE THREAD

**Issue by hacker6010** [platomav/BIOSUtilities#11]
Alienware_ x15_ X17 cannot use Dell_ PFS_ Extract extract，I can use the writeromfile command to decompress normally, but the decompressed file is opened with WinHex. It seems that the content is encrypted and cannot be synthesized with the backup program normally, After my repeated tests, I found that many new Alienware series programs cannot be extracted normally. Can you help solve this problem? Or develop a corresponding program.

**Comment by platomav** [comment]
This is not an issue. If that image is not PFS, then it's not PFS. You should ask at BIOS-related forums/communities to help you out.

**Comment by hacker6010** [comment]
Thank you for your reply. You are quite professional in this regard. Can you recommend a well-known BIOS forum?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "platomav/BIOSUtilities"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月27日(星期天) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [platomav/BIOSUtilities] Alienware_ x15_ X17 cannot use Dell_ PFS_ Extract extract. (Issue #11)





 
This is not an issue. If that image is not PFS, then it's not PFS. You should ask at BIOS-related forums/communities to help you out.

**Comment by platomav** [comment]
bios-mods, mydigitallife, win-raid come to mind right now
