### ISSUE TITLE
Dell PFS Extractor finishes execution without errors, even though no output is generated

### ISSUE THREAD

**Issue by pranav-bhatt** [platomav/BIOSUtilities#12]
Hi! I tried running the Dell PFS Extractor on both XPS 15 BIOS [v1.6.0](https://dl.dell.com/FOLDER06082477M/1/XPS_7590_1.6.0.exe) and [v1.15.0](https://dl.dell.com/FOLDER08002709M/1/XPS_7590_1.15.0.exe), using the following command:
```
.\Dell_PFS_Extract.exe -i .\XPS_7590_1.6.0.exe -o test.txt -v
```

The only terminal output I got was 
```
Dell PFS Update Extractor v5.1

Done!
```

However, no output was generated. Could you check if you are facing this issue as well? The weird thing is that the OP of [this guide](https://www.reddit.com/r/Dell/comments/fzv599/xps_7590_160_uefi_unlock_undervolting_and_remove/) has said that he or she was able to use your tool to extract the relevant information. Am I missing something here?

**Comment by pranav-bhatt** [comment]
Ok so after debugging the code, basically I realized that one needs to pass a directory for it to work, not the path to the file itself. Is this a bug or a design choice?

**Comment by platomav** [comment]
You can run the utility with -h or --help parameter to understand how it works. The parameters are also clearly explained at the README > Dell PFS Update Extractor > Usage.
