### ISSUE TITLE
What if someone extract PE Overlay of Update file before using your script?

### ISSUE THREAD

**Issue by PCRider** [platomav/BIOSUtilities#13]
before finding your code i was trying to do it myself and i find out main part of PE executable  bios update is the overlay, it is easy to extract overlay from a PE COFF file, i did it and then by searching  the file's header i found your work: AMI_UCP_Extract.py
although it was successful to extract the bios from the executable update file but it couldn't extract it from extracted overlay
because in extracted overlay @UAF header began in location 0 so line 515 (if not main_uaf_off:) will fail although 0 is the location of @UAF

anyway i found an opportunity to say thanks for your work
good job

**Comment by platomav** [comment]
Thank you for your kind words and for the bug report! You're right, I've now fixed the offset 0x0 issue at the latest AMI UCP Update Extractor ([f5905ec](https://github.com/platomav/BIOSUtilities/commit/f5905ec662e39f4bffe3f597e8d9271238555edd)) 😃
