### ISSUE TITLE
Nothing populates into my output folder.

### ISSUE THREAD

**Issue by elzorroazul777** [platomav/BIOSUtilities#15]
This could very well be user error, as this is my first stab at running a Python script. Is there something I am missing?https://imgur.com/a/fiv8FFg I am trying to execute this on an .exe I've downloaded from Lenovo's website for a Pheonix BIOS. 
[n2ouj24w.zip](https://github.com/platomav/BIOSUtilities/files/9883628/n2ouj24w.zip)

**Comment by platomav** [comment]
A .exe file is not a "directory". Wrong usage.
