### ISSUE TITLE
Dell Poweredge T105 - Error: This is not a supported input!

### ISSUE THREAD

**Issue by dribgnikcom** [platomav/BIOSUtilities#18]
The BIOS can be found here:

[https://dl.dell.com/bios/PET105-BIOS_WIN_01.04.04.EXE](https://dl.dell.com/bios/PET105-BIOS_WIN_01.04.04.EXE)

Is there a way to extract the ROM?  It has a unique microcode for a specific processor I'd like to extract.  Thanks

**Comment by platomav** [comment]
That BIOS is ancient, well before Dell PFS format. Thus, out of scope for this project. Will go ahead and close this issue.
