### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by sebastiannielsen** [platomav/BIOSUtilities#2]
Why publish virus on site?
https://www.virustotal.com/#/file/84a1ad9e9ffa0e436c5225ba64e7782abc80c4a7c4a32ab7d4d324ebcffb5cd5/detection

**Comment by platomav** [comment]
Obviously false positive. Everything is open source with freeze/build/compile instructions. Review the code and create the executable yourself if you like.

**Comment by sebastiannielsen** [comment]
aah thanks, it worked to use the python code directly with a self-installed python intepreter without the antivirus reacting. Strange that the EXE gives off a virus warning then.
