### ISSUE TITLE
Dell BIOS extractor doesn't work with the DELL inspiron 7415

### ISSUE THREAD

**Issue by cleanbaja** [platomav/BIOSUtilities#20]
When I run `DELL_PFS_Extractor.py` on the BIOS [here](https://dl.dell.com/FOLDER07348959M/1/Inspiron_7415_2-in-1_1.2.0.exe), the format is apparently not recognized. Could you tell me as to why this is?

**Comment by platomav** [comment]
Because it's not PFS, but Insyde IFD.
