### ISSUE TITLE
What tool do I use to decompress HP ProBook 430 G7 Stock EC & BIOS from hp.com?

### ISSUE THREAD

**Issue by CE1CECL** [platomav/BIOSUtilities#21]
It has everything it seems, just in a different, compress and maybe encrypted order?
[sp143205.exe.zip](https://github.com/platomav/BIOSUtilities/files/10728412/sp143205.exe.zip)
[sp143205.zip](https://github.com/platomav/BIOSUtilities/files/10728415/sp143205.zip)

**Comment by CE1CECL** [comment]
This helped me: https://www.bioscreator.com/manual/how-to-decrypt-encrypted-hp-bios-firmware/ but it doesn't come with FD it seems. Since I have a backup, I can manually inject it.

**Comment by CE1CECL** [comment]
it seems its still not valid, ME is still on the bottom rather than the top.

**Comment by platomav** [comment]
This issue is not related to any utility provided in this repo, maybe someone can help you are relevant forums, such as [win-raid](https://winraid.level1techs.com/). I'm thus closing this issue.
