### ISSUE TITLE
Dell_PFS_Extract.py script is not working

### ISSUE THREAD

**Issue by becauro** [platomav/BIOSUtilities#22]
Hi, guys!

I've tried use the [Dell_PFS_Extract.py](https://github.com/platomav/BIOSUtilities/blob/main/Dell_PFS_Extract.py) script to extract a [dell bios](https://www.dell.com/support/home/pt-br/drivers/driversdetails?driverid=2v5ry), but that seems is not working, despite it doesn't print out any error message.

The script just end as if it was successful, however nothing is extracted.

I tested it under Windows 10 and Ubuntu 22.04...

Thank you for any help! 🚀

**Comment by platomav** [comment]
All scripts clearly indicate unexpected inputs via the "Error: This is not a supported input!" message. That package is not Dell PFS, but rather AMI UCP.

**Comment by becauro** [comment]
> All scripts clearly indicate unexpected inputs via the "Error: This is not a supported input!" message. That package is not Dell PFS, but rather AMI UCP.

Yes ...

However, by using the **--input-dir** argument, it doesn't  throw **"Error: This is not a supported input!"** message.
It seems a condition for checking **--input-dir** argument is not implemented on this project yet.
