### ISSUE TITLE
--input-dir argument

### ISSUE THREAD

**Issue by becauro** [platomav/BIOSUtilities#23]
Hi !

Here is a "little" feedback for this great project.

It seems a checking for **--input-dir** argument is not implemented yet, despite that is listed in the scripts help.

- By using the --input-dir argument along the wrong file, it doesn't throw "Error: This is not a supported input!" message in ANY script.
- Although the script receives the correct file for extraction, just for passing a **--input-dir** argument to it, the script doesn't perform extraction anymore. At least that was what happen with [AMI_UCP_Extract.py](https://github.com/platomav/BIOSUtilities/blob/main/AMI_UCP_Extract.py) when using it along [this bios](https://www.dell.com/support/home/pt-br/drivers/driversdetails?driverid=2v5ry).

**NOTE 1 (Ergonomics):** That's an ergonomic point, specially for newbies on "Bios Mod" (or Python language).

**NOTE 2 (BUG):** Passing the correct argument (and correct BIOS file) to the correct script and getting incorrect result is a bug. Even if this argument is OPTIONAL.

Thanks 🚀

**Comment by platomav** [comment]
Please show how exactly you're trying to use/run a given script using "--input-dir" parameter.

**Comment by becauro** [comment]
Okay...

**All manners I used it under Ubuntu 22.04**


`python3 script.py --input-dir folderA/bios.exe -o folderB`
 
 or (with ./):

`python3 script.py --input-dir ./folderA/bios.exe -o folderB`

 or (with single quotes):

`python3 script.py --input-dir 'folderA/bios.exe' -o folderB`

 or (with single quotes and ./):

`python3 script.py --input-dir './folderA/bios.exe' -o folderB`

===

**NOTE:** I also tested all of those options along with `-i `parameter and **between quotes ("")**

**Comment by becauro** [comment]
Now I tested like this `python3 script.py --input-dir './folderA' -o folderB` (by ommiting the bios file name ) and that worked.

Well... That way is different for me.

So, If that is the correct way, just move on and abort my suggestions.

**Comment by platomav** [comment]
Yes, the issue was wrong usage of the parameter. As its same and description explain ("extract from given input directory"), it works with directories/folders, not files.
