### ISSUE TITLE
Scripts aren't marked as executable 

### ISSUE THREAD

**Issue by shmalebx9** [platomav/BIOSUtilities#25]
Leah and I are planning on integrating this utility into [Libreboot's build system.](https://codeberg.org/libreboot) We can maintain a patch to mark all scripts as executable on our end if there's a reason you don't want to do it here.

**Comment by platomav** [comment]
No specific reason, just difficulties when pushing changes from Windows vs Linux OS. It could happen that the chmod +x is forgotten in one commit. To avoid such mistakes, it might be more robust to have a tiny patch which sets their mode as "x", to be sure. From my quick online search today, I did not find a way to add this as a git attribute, but feel free to correct me if I'm wrong.
