### ISSUE TITLE
Input error?

### ISSUE THREAD

**Issue by kondenguoter** [platomav/BIOSUtilities#26]
I am trying to extract the bios from a Alienware Aurora R7 using this tool.
I drag & drop Alienware_Aurora_R7_1.0.20.exe onto Dell_PFS_Extract.py, but then I get this Error: 'This is not a supported input!'
I am not experienced with Python so it probably is an issue on my side. 

https://user-images.githubusercontent.com/131866942/234544307-0e19ff86-c51e-4ca2-9a18-a990df964118.mp4

**Comment by platomav** [comment]
https://github.com/platomav/BIOSUtilities/issues/24#issuecomment-1462728144
