### ISSUE TITLE
Fujitsu UPC tianocore error

### ISSUE THREAD

**Issue by htm23x** [platomav/BIOSUtilities#27]
Hi, I'm trying to decompress a Fujitsu UPC bios update but your python Fujitsu_UPC_Extract.py gives a Tianocore error parsing the UPC files inside that bios file.

May you download and extract that bios and try to parse with your tool , pls?
 
[D3235.zip](https://github.com/platomav/BIOSUtilities/files/12022885/D3235.zip)

Many thanks.

**Comment by platomav** [comment]
![Screenshot 2023-08-01 223256](https://github.com/platomav/BIOSUtilities/assets/11527726/160191a8-7c70-438b-9821-6580f204098f)
