### ISSUE TITLE
 Error: This is not an AMI BIOS Guard (PFAT) image! HELP

### ISSUE THREAD

**Issue by farmeldotner** [platomav/BIOSUtilities#32]
Hello I have Asus Rog Zephyrus M16 2021 GU603HE.
I usually left open my laptop. Last week when I entered the room I noticed computer was in bios and will be upgrading it bios version in 30 second.
I rushed it and hold the power button because I don't want it to be updated. After 5 seconds bios update started and in the 6. second computer shotted down.
After this moment nothing comes the screen. Keyboard lights are on and fans are spinning.

I bought CH341A and manage to read the bios chip. Made few changes, tried different things and reprogrammed it but nothings changed.

Also I couldn't analyze official bios because it says "AMI BIOS Guard (PFAT) protected image". And I couldn't remove the protection. It says " Error: This is not an AMI BIOS Guard (PFAT) image!"

What should I do any suggestions? Can someone help me?

[ASUS GU603HE 315 BIOS OFFICIAL SITE](https://dlcdnets.asus.com/pub/ASUS/GamingNB/GU603HE/GU603HEAS315.zip?model=ROG%20Zephyrus%20M16%20GU603)

**Comment by farmeldotner** [comment]
Here is my bios.
[mybios.bin](https://drive.google.com/file/d/1R8V0ezBfCHXCSAKzkNOu9Umfc2l9ftrR/view)

**Comment by platomav** [comment]
As this is not an issue related to the functionality of AMI BIOS Guard Extractor, and by extension this repository, I suggest you ask for help/suggestions at forums such as [Win-Raid](https://winraid.level1techs.com/), [BIOS-Mods](https://www.bios-mods.com/forum/), [MyDigitalLife ](https://forums.mydigitallife.net/) etc.
