### ISSUE TITLE
Panasonic extract script not extracting .bin for CF-33 Mk2

### ISSUE THREAD

**Issue by Wasmachineman-NL** [platomav/BIOSUtilities#33]
Title. It only gives me a .exe to flash the BIOS itself.

https://i.imgur.com/ArwjgE4.png

**Comment by platomav** [comment]
I was able to find the link to download the update [here](https://pc-dl.panasonic.co.jp/dl/docs/081942?dc%5B%5D=002003&no=10&q=cf-33&score=1.03059244155884&sri=22162375&trn_org=2). You also haven't shown what is the progress output of utility. Please provide such info in the future to assist others with helping you.

I don't see any problem, the utility works just fine. Make sure you have cloned the entire BIOSUtilities repo and that you have installed all the dependencies needed for the Panasonic utility to run, as explained at the README:

https://github.com/platomav/BIOSUtilities?tab=readme-ov-file#panasonic-bios-package-extractor

**Comment by Wasmachineman-NL** [comment]
I have all dependencies installed and CF-19 BIOSes extract just fine, so I dunno what you're talking about?

**Comment by Wasmachineman-NL** [comment]
Wow i'm retarded, and too impatient. I had to wait a few more seconds despite the program saying it was done extracting.
