### ISSUE TITLE
virustotal  9 engines detected this file Dell_PFS_Extract.exe in Dell_PFS_Extract_v4.2.rar 

### ISSUE THREAD

**Issue by comicsheep** [platomav/BIOSUtilities#4]
1.Unzip Dell_PFS_Extract_v4.2.rar to get Dell_PFS_Extract.exe
2.upload Dell_PFS_Extract.exe to virustotal
3.9 engines detected this file

- SecureAge APEX Malicious
- Bkav W32.AIDetectVM.malware
- Cylance Unsafe
- FireEye Generic.mg.b2373cd5abfeda74
- McAfee-GW-Edition BehavesLike.Win32.TrojanVeil.rc
- Rising Trojan.Generic@ML.90 (RDML:M8naQWlg0ABaoQLkLq8TWA)
- SentinelOne (Static ML) DFI - Suspicious PE
- Sophos ML Heuristic
- Trapmine Suspicious.low.ml.score
https://www.virustotal.com/gui/file/ce9de5079e41a43893510bb249e1308c773bf5ae2775a9364b330e592c3a6d54/detection

Supply chain attack or just false positive?

**Comment by platomav** [comment]
https://github.com/platomav/BIOSUtilities#anti-virus-false-positives
