### ISSUE TITLE
PFAT Extract, input not supported

### ISSUE THREAD

**Issue by sanOK147** [platomav/BIOSUtilities#43]
Hi there,
First of all, many thanks for the great tool, really cool! I just encountered one small problem and I really hoped you could help me a little. While trying to open a new Asus X409JA bios (310 file type) with PFAT_Extract, it says that file type is not correct.... Is there a way to fix it somehow (sorry for a rookie question, I'm really new to python)?

![image](https://github.com/platomav/BIOSUtilities/assets/171564082/7a8ae56b-d9e0-4cb0-ab4b-2803e2edd09e)

**Comment by platomav** [comment]
The input is not AMI PFAT

https://github.com/platomav/BIOSUtilities/issues/24#issuecomment-1462728144
