### ISSUE TITLE
Error with python, No module named 'common.checksums'

### ISSUE THREAD

**Issue by TheSpecialAussie** [platomav/BIOSUtilities#44]
Are there any modules we need to install via pip, as I cannot continue as I dont have the required modules I believe.

![image](https://github.com/platomav/BIOSUtilities/assets/173656826/8ff5a709-0718-4fb5-8ba0-8a2697479332)

**Comment by platomav** [comment]
"common" is a folder, not a 3rd party module or dependency. Make sure you have cloned the entire repository first.
