### ISSUE TITLE
Doesn't seem to work for bios on Acer Nitro 5

### ISSUE THREAD

**Issue by Kreyren** [platomav/BIOSUtilities#45]
Referencing: https://github.com/flashrom/flashrom/issues/220#issuecomment-2043528027

The system's previous SPI chip blew and caused damage to some passive components that were replaced and i can't see any other issues on the board right now, but it still ends up in the 'braindead' state as if it had a bad mainboard firmware so i assume that the tool used didn't extract the firmware correctly.

CC @platomav

**Comment by platomav** [comment]
There is nothing wrong with the output of the Insyde IFD Extractor. I can verify the sha256 of the BIOS region firmware extracted and the Insyde IFD structure is fairly simple without any compression or similar.
