### ISSUE TITLE
No Output On Asus G16 2024 GU-605MZ . [AMI_PFAT_Extract]

### ISSUE THREAD

**Issue by kisenaa** [platomav/BIOSUtilities#46]
Hello, Good morning. Thank you for this awesome tool. But i'm having trouble extracting AMI PFAT BIOS from Asus G16 2024 GU-605MZ . When I ran the program, I didn't get any output file / directory.

```
D:\Documents\BIOS\BIOSUtilities-main\BIOSUtilities-main>python ./AMI_PFAT_Extract.py -i D:\Documents\BIOS\Asus_G16_GU605MZ\GU605MZAS.319.bin -o D:\Documents\BIOS\Asus_G16_GU605MZ
AMI BIOS Guard Extractor v6.0

Done!

D:\Documents\BIOS\BIOSUtilities-main\BIOSUtilities-main>cd D:\Documents\BIOS\Asus_G16_GU605MZ

D:\Documents\BIOS\Asus_G16_GU605MZ>dir
 Volume in drive D is D Drive
 Volume Serial Number is 4237-6939

 Directory of D:\Documents\BIOS\Asus_G16_GU605MZ

08/07/2024  13:51    <DIR>          .
08/07/2024  13:52    <DIR>          ..
08/07/2024  13:51        14.788.472 ASUS_GU605MZ_319_BIOS_Update.exe
08/07/2024  13:50        38.928.384 GU605MZAS.319.bin
               2 File(s)     53.716.856 bytes
               2 Dir(s)  3.744.764.030.976 bytes free

D:\Documents\BIOS\Asus_G16_GU605MZ>python --version
Python 3.10.11
```
Here is the zipped bin file from [asus support sites](https://dlcdnets.asus.com/pub/ASUS/GamingNB/Image/BIOS/116518/GU605MZAS319.zip?model=ROG%20Zephyrus%20G16%20(2024)) :
[GU605MZAS319.zip](https://github.com/user-attachments/files/16123821/GU605MZAS319.zip)

I confirmed that the .bin file has a string AMIPFATcAMI_BIOS_GUARD_FLASH_CONFIGURATION in the beginning by using HXD editor. Did i do something wrong ? Thank you

**Comment by platomav** [comment]
Hello,

Yes, you're using the -i parameter in the wrong way:

https://github.com/platomav/BIOSUtilities/issues/23#issuecomment-1460652416

**Comment by kisenaa** [comment]
> Hello,
> 
> Yes, you're using the -i parameter in the wrong way:
> 
> [#23 (comment)](https://github.com/platomav/BIOSUtilities/issues/23#issuecomment-1460652416)

Thank you. I have another question. If I want to assemble _ALL.bin back to AMI PFAT IMAGES, then I need to understand the bios structure and modify the python code ?  
Or is similar tool already exist ?. Thanks

**Comment by platomav** [comment]
As explained in the README, the "ALL" file simply merges together all the other files extracted from the PFAT image. It may not be representative of a usable/flashable blob. This changes from case to case, and it's up to the user to determine its usefulness, if any.
