### ISSUE TITLE
Add support for AMI EFI update capsules

### ISSUE THREAD

**Issue by Peax** [platomav/BIOSUtilities#49]
Hi,

I stumbled upon a "new" format of BIOS capsules from AMI. The principle looks similiar to [Portwell EFI Update Extractor](https://github.com/platomav/BIOSUtilities?tab=readme-ov-file#portwell-efi-update-extractor), where the capsule is packed inside an EFI file. The capsule itself contains both BIOS and EC firmware.

The following examples are from Tongfang notebook barebones. Naming scheme is as follows:

```
GMxIX9xN110A10_CAP.efi
|      |   |
|      |   +--> A10: Reseller customizations
|      +-----> N110: BIOS version N1.10
+---------> GMxIX9x: barebone model, e. g. GM7IX9N
``` 

**AMI EFI capsule examples:**

- [AMI_EFI_BIOS_Capsule_Intel_13th_gen.zip](https://github.com/user-attachments/files/16910726/AMI_EFI_BIOS_Capsule_Intel_13th_gen.zip)
- [AMI_EFI_BIOS_Capsule_Intel_14th_gen.zip](https://github.com/user-attachments/files/16910727/AMI_EFI_BIOS_Capsule_Intel_14th_gen.zip)

Adding support for this format would be great :)

**Comment by platomav** [comment]
Hello,

It's actually AMI UCP format, a utility already exists for that

**Comment by Peax** [comment]
sorry, me stupid 🙈
