### ISSUE TITLE
Failure to detect Intel BIOS Guard Signature length of Dell XPS 13 9350

### ISSUE THREAD

**Issue by platomav** [platomav/BIOSUtilities#50]
https://fwupd.org/lvfs/devices/com.dell.uefi1a99170e.firmware

[firmware.zip](https://github.com/user-attachments/files/16918700/firmware.zip)

**Comment by westlake-san** [comment]
Same problem.

[ASUS, Lunar Lake](https://dlcdnets.asus.com/pub/ASUS/Commercial_NB/Image/BIOS/117663/ASUS_P5405CSA_303_BIOS_Update.exe?model=P5405CSA)

AMI BIOS Guard Extractor v6.0

"Error: Could not detect Intel BIOS Guard Signature length, assuming 3K!"

**Comment by platomav** [comment]
Added proper support for the new feature as part of BIOSUtilities v24.10.01 release [cda2fbd](https://github.com/platomav/BIOSUtilities/commit/cda2fbd0b1637207b62a82b31606bf2ab5ebfecb)
