### ISSUE TITLE
A few PATH related quaries

### ISSUE THREAD

**Issue by coredex-source** [platomav/BIOSUtilities#51]
Hey!
I was using the previous version of BIOSUtilities using a menu driven program I made, I wont need that anymore and it will defiantly make it a bit easier to use .. but, I switch PCs a lot during a single day of operation. A have a few quarries here - 

Q.1. Can't I use it with a similar external folder as before (I don't want to setup the path variables on every PC.) ?
Q.2. Can I use user-specific path or do I "need" to use system-wide path ?

**Comment by platomav** [comment]
Hi,

Thank you for the feedback. I released v24.10.03 with support for a non-PATH flow. It should cover your use-case nicely.

**Comment by coredex-source** [comment]
I really appreciate all the efforts you put into the tool, thank you very much for adding the folder support again.
