### ISSUE TITLE
Error with Python 3.13.0

### ISSUE THREAD

**Issue by westlake-san** [platomav/BIOSUtilities#52]
Worked fine with Python 3.12.7, but not with 3.13.0. Pefile is installed (2024.8.26).

![error](https://github.com/user-attachments/assets/65501e03-ebc1-450e-b7fa-b826a4eda9a4)

**Comment by platomav** [comment]
The error indicates that you do not have the pip requirements installed at Python 3.13. Also:

- Use the latest release (2024.10.07 as of now)
- Use pefile 2023.2.7 and not 2024.8.26
  - Was downgraded as part of BIOSUtilities 2024.10.07
  - The project has not been tested with (the brand new) Python 3.13. Only Python 3.10-3.12 versions have been validated.

**Comment by westlake-san** [comment]
BIOSUtilities 2024.10.07 and pefile 2023.02.07. So it does not currently work with Python 3.13.0.

![error2](https://github.com/user-attachments/assets/7385a549-9776-43ad-9582-fab2b1e58e88)

**Comment by platomav** [comment]
If you have more than 1 Python installation, you need to make sure you're calling the correct pip module. As you can see, the path where pefile module was found is under python3.12 and not 3.13.

**Comment by westlake-san** [comment]
That's how much I know about Python. I just upgraded from the previous version to the newer one (3.12.7 -> 3.13.0), I didn't expect it to happen in this form. The logical thing would have been to overwrite the existing version, not create a new one. In any case, it works fine now (uninstall -> install).

**Comment by platomav** [comment]
Python 3 was released in 2008. It is the minor versions which indicate the actual branch/release. Only the hotfix releases behave as you indicate.

For example, 3.12.5 will be overwritten by 3.12.7. However, 3.13 is a new branch with new but potentially also breaking and/or deprecated features. Thus, 3.12 is one installation and 3.13 another. Python 3.12 will continue to receive new features for some time, then bugfixes only and then EoL, just like previous Python release cycles:

https://devguide.python.org/versions/

It is no different than Windows release cycles really.
