### ISSUE TITLE
Missing dependancies

### ISSUE THREAD

**Issue by UltraShadoww** [platomav/BIOSUtilities#54]
I'm trying to extract the bios of a ASUS TUF 15 FXF1ZR to obtain the VBT and the GOP files. 
When I use BIOSUtilities I get the following error: 
  Note: BIOS Guard Script Tool optional dependency is missing!

I have already put the big_script_tool.py in the external folder and I've also added it to usr/local/bin and /bin/, I've also tried adding it to the path on both windows and linux but to no avail. 

Please help me figure out how to get hostilities working properly with it's dependencies.

**Comment by coredex-source** [comment]
I am fairly positive that it won't extract using this tool, now for your error, where have you put the external folder at ? as the latest version of the software works just fine for me using the external folder.

**Comment by platomav** [comment]
That's a note, neither a warning nor an error. It does not affect anything, as the message helpfully indicates: "optional".

If you want to parse and view the BG script (you almost certainly don't), make sure the "big_script_tool.py" is at the correct folder (external at the root of the project or accessible/detectable via $PATH).

Where is the project installed (run from)? Where is the "external" folder (if you opted to use that approach)?
