### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by westlake-san** [platomav/BIOSUtilities#55]
It works fine with 241007, but not with newer versions (241009, 241017).

![241007](https://github.com/user-attachments/assets/580f018f-d1d1-4532-a871-bfb43559a2e0)

![241009](https://github.com/user-attachments/assets/d4bf4f97-544e-4400-8473-34a4a61f1078)

It must be something general if it is already stuck at AMI UCP.

**Comment by platomav** [comment]
Thanks for the report! Should be fixed at v24.10.18 (https://github.com/platomav/BIOSUtilities/commit/35455f735c034399eea1c3b3abca067583a20bcf)
