### ISSUE TITLE
Unable to extract BIOS file for ASUS FX506LI.310

### ISSUE THREAD

**Issue by gokulmunusamy** [platomav/BIOSUtilities#57]
I'm trying to extract a BIOS file for my ASUS FX506LI using the BIOSUtilities tool. However, I keep running into issues where the script completes without actually extracting any files. Here are the details:

OS: Windows 11

Python version: 3.11.4

Steps I followed:

Cloned the BIOSUtilities repository.

Installed all dependencies using pip install -r requirements.txt.

Ran the script with the following command:

bash

Copy
python.exe .\main.py -o "C:\Users\gokul\OneDrive\Desktop\ASUS\new" "C:\Users\gokul\OneDrive\Desktop\ASUS\new\FX506LI-AS.310"
Script Output:

plaintext

Copy
Starting script...
Initializing...
Input files: ['C:\\Users\\gokul\\OneDrive\\Desktop\\ASUS\\new\\FX506LI-AS.310']
Output directory: C:\Users\gokul\OneDrive\Desktop\ASUS\new
FX506LI-AS.310
Script completed.
Issue:

The script runs and completes, but no files are extracted.

The BIOS file is valid and confirmed not corrupted.

Verified the output directory and file paths are correct.

Attempts to Resolve:

Added print statements for debugging to confirm paths and file processing.

Tried running with elevated permissions.

Re-verified file integrity and paths.

Any guidance or suggestions would be greatly appreciated!

**Comment by platomav** [comment]
What exactly are you trying to extract using BIOSUtilities? This is simply an UEFI image with an AMI Capsule. There is nothing to do with utilities from this repo.
