### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by westlake-san** [platomav/BIOSUtilities#58]
If I understand correctly, it does not like files that are not supported. If only supported files are in the directory, it will not run on error. 24.10.23 works fine, but the two newer ones do not. 

![error](https://github.com/user-attachments/assets/96cabbdf-fb97-410f-878e-83d7212121d5)

**Comment by platomav** [comment]
The error indicates that you lack requirements

https://github.com/platomav/BIOSUtilities?tab=readme-ov-file#external-executables--scripts
