### ISSUE TITLE
Issue with Dell FPS extractor

### ISSUE THREAD

**Issue by LocTran016** [platomav/BIOSUtilities#6]
Excuse me. I'm using Dell Inspiron 3421 and I want to extract my A13 BIOS via the Python Script but failed, I'm using MacOS 10.15.6 so my python is newer than 3.7.0
The BIOS is here: [DELL INSPIRON 3421 A13 BIOS](https://www.dell.com/support/home/en-vn/drivers/driversdetails?driverid=dcgmv&oscode=w764&productcode=inspiron-14-3421)
Thanks for reading my message
![image](https://user-images.githubusercontent.com/64778285/90374476-c0f52500-e09d-11ea-8f61-c955e1209741.png)

**Comment by platomav** [comment]
As the error says, the loaded BIOS is not in PFS format so Dell FPS Extractor is obviously not applicable to it. You can run the executable under Windows with the command **/writehdrfile** instead.
