### ISSUE TITLE
'AMI BIOS Guard Extractor' or 'AMI UCP BIOS Extractor' not working for Lenovo BIOS

### ISSUE THREAD

**Issue by chaoscreater** [platomav/BIOSUtilities#8]
Hi, 

Thanks for making these tools. I've tried the Dell BIOS Extractor and got it working for my Dell Optiplex 3080. I'm trying to do the same thing but for my Lenovo M92p Tiny and I've tried using both the AMI BIOS Guard Extractor and AMI UCP BIOS Extractor and neither are able to extract any useful files from my Lenovo BIOS.......My Lenovo BIOS definitely use AMI.

You can find the BIOS from here:
https://support.lenovo.com/au/en/downloads/ds029265-flash-bios-update-thinkcentre-edge-92-thinkcentre-m82-m92-and-m92p-thinkstation-e31

I'm using the already compiled .exes from your Releases page. Please let me know what I'm doing wrong, or whether your tool actually supports that BIOS version, thanks!

**Comment by platomav** [comment]
This is not an issue. If that firmware is not PFAT or UCP, then it's not PFAT or UCP. You should ask at BIOS-related forums/communities to help you out.
